version: "3"
services:
  eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}:/app
      - ${PWD}/../text/faq:/app/faq
      - ${PWD}/../text/privacypolicy.md:/app/text/privacypolicy.md
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npx -p @11ty/eleventy eleventy --watch --serve
    ports:
      - 8080:8080
